### ISSUE TITLE
Mailgun domain deletion fails on timeout

### ISSUE THREAD

**Issue by kiweezi** [pulumi/pulumi-mailgun#119]
### What happened?

When deleting a Mailgun domain, the domain is deleted in Mailgun, but Pulumi thinks it still exists.
Creating domains works as normal.

Deletion:
```powershell
Diagnostics:
  mailgun:index:Domain (foo.my.test.app):
    error: deleting urn:pulumi:foo::customer::mailgun:index/domain:Domain::foo.my.test.app: 1 error occurred:
        * domain seems to still exist; will check again
```

Subsequent deletions or refreshes:
```powershell
Diagnostics:
  mailgun:index:Domain (foo.my.test.app):
    error: deleting urn:pulumi:foo::customer::mailgun:index/domain:Domain::foo.my.test.app: 1 error occurred:
        * Error deleting domain: UnexpectedResponseError URL=https://api.eu.mailgun.net/v3/domains/foo.my.test.app ExpectedOneOf=[]int{200, 202, 204} Got=404 Error: {"message":"Domain not found"}
```

### Expected Behavior

Deleting a domain using the Mailgun provider for Pulumi.

### Steps to reproduce

1. Code a Mailgun domain in Pulumi
2. Run `pulumi up`
3. Run `pulumi destroy`

### Output of `pulumi about`

```
PS pulumi> pulumi about
CLI
Version      3.58.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.67.0
azuread       5.36.0
mailgun       3.4.1
opsgenie      1.1.6
python        unknown
random        4.8.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in python: executable='C:\Program Files\Python310\python.exe' version='3.10.2
'

Current Stack: juriba/customer/foo

...

Found no pending operations associated with juriba/foo

Backend
Name           pulumi.com
URL            https://app.pulumi.com/kiweezi
User           kiweezi
Organizations  kiweezi, juriba, ricochet-studios

Dependencies:
NAME                 VERSION
pip                  23.0.1
pulumi-azure-native  1.67.0
pulumi-azuread       5.36.0
pulumi-mailgun       3.4.1
pulumi-opsgenie      1.1.6
pulumi-random        4.8.0
setuptools           67.6.0
wheel                0.40.0

Pulumi locates its logs in C:\Users\myuser\AppData\Local\Temp by default
warning: A new version of Pulumi is available. To upgrade from version '3.58.0' to '3.60.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Additional context

The initial deletion works and the domain is no longer seen in Mailgun, but Pulumi thinks it has failed. This means the state is out of date and the urn must be deleted from it, before you can continue. Refreshes also fail with the above. I checked the issues on the Terraform repo and see nothing related, so I believe this just exists for Pulumi.

It also seems to run for around 70 seconds before failing, which sounds to me like a timeout.
The domain can be created just fine.

You can work around this issue with the following:
1. Let the deletion fail.
2. Delete the urn from the state:
```powershell
pulumi state delete urn:pulumi:mystack::myproject::mailgun:index/domain:Domain::my.domain.name
```
3. Run the deletion again.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @kiweezi - thank you so much for sending this issue!

I hope you don't mind I double-checked with upstream and [found the following issue](https://github.com/wgebis/terraform-provider-mailgun/issues/39).

This seems to be a mismatch between the resource timeout and the amount of time it takes the Mailgun API to remove a domain.

Since you've already posted the workaround, I will mark this issue as blocked upstream.

**Comment by kiweezi** [comment]
Thanks @guineveresaenger and sorry I didn't see that related issue, I feel like an idiot!
Will continue my conversation on there. Thank you for your help!

**Comment by aq17** [comment]
Update: issue has been fixed upstream, but blocked on maintainer cutting a new release.

**Comment by mikhailshilkov** [comment]
It sounds like the upstream issue has been fixed a while ago, so I'll go ahead and close this as done too
